baseURL = "https://joaovsbuarque2.github.io/joaobuarque-thinking/"
defaultContentLanguage = "pt-br"
theme = "LoveIt"

[taxonomies]
  category = "categories"
  tag = "tags"

[languages]
  [languages.pt-br]
    languageCode = "pt-br"
    languageName = "Português (Brasil)"
    title = "João Buarque Thinking"
    weight = 1

  [languages.en]
    languageCode = "en"
    languageName = "English"
    title = "João Buarque Thinking"
    weight = 2
